# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.kernelPackages = pkgs.linuxPackages_cachyos-rc;
  services.scx.enable = true;
  services.scx.scheduler = "scx_lavd";
  chaotic.mesa-git.enable = true;

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];
  boot.binfmt.emulatedSystems = ["aarch64-linux"];
  boot.kernelParams = [
    "amd_iommu=on"
  ];

  hardware.firmware = [
    (pkgs.stdenv.mkDerivation {
      name = "edid-custom";
      src = ./deez;
      installPhase = ''
        mkdir -p $out/lib/firmware/edid
        cp g80sd_4k_240.bin $out/lib/firmware/edid/
      '';
    })
  ];

  hardware.display = {
    outputs."DP-2".edid = "g80sd_4k_240.bin";
    outputs."DP-2".mode = "e";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/300ab82a-de51-4f81-84cf-52c706b94ff3";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5740-A46C";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  virtualisation.spiceUSBRedirection.enable = true;

  swapDevices = [];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
