# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];

  # from cachyos
  boot.kernelPackages = pkgs.linuxPackages_cachyos-rc;
  services.scx.enable = true;
  services.scx.scheduler = "scx_lavd";

  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # temp amd input lag fix framework 13
  # https://community.frame.work/t/keyboard-is-laggy-on-linux-6-12-only/61736/5
  boot.kernelParams = [
    "amdgpu.dcdebugmask=0x10"
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ae99757b-283c-4ee1-be21-f219d9909a1d";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C5E0-C3F8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
